package com.Kungfu.panda.entity;

import  jakarta.persistence.*;
import lombok.Data;


@Entity
@Table(name = "customers")
@Data
public class Customers {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long customer_id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private Users users;

    @Column(nullable = false)
    private String address;

    @Column(nullable = false, unique = true)
    private String phone;

    // Constructors, getters, and setters can be generated by Lombok's @Data annotation
}
