package  com.Kungfu.panda.entity;

import jakarta.persistence.*;

import java.sql.Timestamp;

@Entity
@Table(name = "customer_orders")
public class CutomerOrders {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long order_id;

    @ManyToOne
    @JoinColumn(name = "customer_id", nullable = false)
    private Customers customers;

    @Column(nullable = false)
    private Timestamp order_date;

    @Column(nullable = false)
    private Double amount;

    // Constructors, getters, and setters can be generated by Lombok's @Data annotation
}